import fs from "node:fs";
import * as snarkjs from "snarkjs";
import {
  MerkleSumTree,
  buildPrivateInput,
  encodeProof,
  encodeVerifyingKey,
  fieldToBytes,
} from "../../sdk/dist/index.js";

const LIAB_DEPTH = 4;
const RES_DEPTH = 3;
const BUILD = "build/psolvency_demo";
const OUT_RS = "../contracts/contracts/attestar/src/fixtures.rs";

const vkey = JSON.parse(fs.readFileSync(`${BUILD}/psolvency_demo.vkey.json`, "utf8"));

// Formats bytes that the SDK already encoded into a Rust array literal. The
// field-element-to-bytes conversion itself lives in @attestar/sdk
// (fieldToBytes / encodeProof / encodeVerifyingKey) so there is exactly one
// implementation in the repository.
const bytes = (u8) =>
  "[" + Array.from(u8, (b) => "0x" + b.toString(16).padStart(2, "0")).join(", ") + "]";
const list = (arrays) => `[\n        ${arrays.map(bytes).join(",\n        ")}\n    ]`;

async function prove(holders, sources, onchain) {
  const liabTree = await MerkleSumTree.build(holders, LIAB_DEPTH);
  const resTree = await MerkleSumTree.build(sources, RES_DEPTH);
  const input = buildPrivateInput(holders, sources, onchain, LIAB_DEPTH, RES_DEPTH);
  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    input,
    `${BUILD}/psolvency_demo_js/psolvency_demo.wasm`,
    `${BUILD}/psolvency_demo.zkey`,
  );
  if (!(await snarkjs.groth16.verify(vkey, publicSignals, proof))) {
    throw new Error("snarkjs verify failed");
  }
  if (BigInt(publicSignals[0]) !== liabTree.root || BigInt(publicSignals[1]) !== resTree.root) {
    throw new Error("public roots do not match SDK");
  }
  if (BigInt(publicSignals[3]) !== onchain) {
    throw new Error("onchain public signal mismatch");
  }
  return {
    proof: encodeProof(proof),
    pub: publicSignals.map((s) => fieldToBytes(s)),
    solvent: publicSignals[2] === "1",
    onchain,
  };
}

const HOLDERS = [
  { userId: 111n, balance: 5000n },
  { userId: 222n, balance: 3000n },
  { userId: 333n, balance: 1500n },
];

const s = await prove(
  HOLDERS,
  [
    { userId: 1n, balance: 4000n },
    { userId: 2n, balance: 3000n },
  ],
  5000n,
);
const i = await prove(HOLDERS, [{ userId: 1n, balance: 1000n }], 2000n);

if (!s.solvent) throw new Error("solvent fixture is not solvent");
if (i.solvent) throw new Error("insolvent fixture is solvent");

const vk = encodeVerifyingKey(vkey);

const rs = `// @generated by packages/circuits/scripts/encode_p.mjs - do not edit by hand.
// Real Groth16 proofs + verifying key for the PrivateSolvency(4,3,64,96) circuit.
// Public signals are [liab_root, res_root, solvent, onchain_reserves].
#![cfg(test)]

pub const ALPHA: [u8; 64] = ${bytes(vk.alpha)};
pub const BETA: [u8; 128] = ${bytes(vk.beta)};
pub const GAMMA: [u8; 128] = ${bytes(vk.gamma)};
pub const DELTA: [u8; 128] = ${bytes(vk.delta)};
pub const IC: [[u8; 64]; ${vk.ic.length}] = ${list(vk.ic)};

// Solvent fixture: onchain 5000 + offchain 7000 >= liabilities 9500.
pub const S_PROOF_A: [u8; 64] = ${bytes(s.proof.a)};
pub const S_PROOF_B: [u8; 128] = ${bytes(s.proof.b)};
pub const S_PROOF_C: [u8; 64] = ${bytes(s.proof.c)};
pub const S_PUB: [[u8; 32]; 4] = ${list(s.pub)};
pub const S_LIAB_ROOT: [u8; 32] = ${bytes(s.pub[0])};
pub const S_RES_ROOT: [u8; 32] = ${bytes(s.pub[1])};
pub const S_ONCHAIN: i128 = ${s.onchain.toString()};
pub const S_SOLVENT: bool = true;

// Insolvent fixture: onchain 2000 + offchain 1000 < liabilities 9500.
pub const I_PROOF_A: [u8; 64] = ${bytes(i.proof.a)};
pub const I_PROOF_B: [u8; 128] = ${bytes(i.proof.b)};
pub const I_PROOF_C: [u8; 64] = ${bytes(i.proof.c)};
pub const I_LIAB_ROOT: [u8; 32] = ${bytes(i.pub[0])};
pub const I_RES_ROOT: [u8; 32] = ${bytes(i.pub[1])};
pub const I_ONCHAIN: i128 = ${i.onchain.toString()};
pub const I_SOLVENT: bool = false;
`;

fs.writeFileSync(OUT_RS, rs);
console.log("wrote", OUT_RS);
console.log("solvent pub:", s.pub.map((b) => Buffer.from(b).toString("hex")).join(","));
console.log("insolvent pub:", i.pub.map((b) => Buffer.from(b).toString("hex")).join(","));
process.exit(0);
