import fs from "node:fs";
import * as snarkjs from "snarkjs";
import {
  MerkleSumTree,
  buildCircuitInput,
  encodeG1,
  encodeG2,
  fieldToBytes,
  toHex,
} from "../../sdk/dist/index.js";

const DEPTH = 2;
const BUILD = "build/solvency_test";
// This legacy depth-2 generator must NOT write the fixtures.rs the contract tests
// import: encode_p.mjs owns that file with an incompatible schema. Keep the
// legacy fixture set in its own file so running this script can never clobber
// the production fixtures.
const OUT_RS = "../contracts/contracts/attestar/src/legacy_fixtures.rs";
const OUT_JSON = `${BUILD}/fixtures.json`;

const holders = [
  { userId: 111n, balance: 5000n },
  { userId: 222n, balance: 3000n },
  { userId: 333n, balance: 1500n },
];

const tree = await MerkleSumTree.build(holders, DEPTH);
const input = buildCircuitInput(holders, DEPTH);

const { proof, publicSignals } = await snarkjs.groth16.fullProve(
  input,
  `${BUILD}/solvency_test_js/solvency_test.wasm`,
  `${BUILD}/solvency_test.zkey`,
);

const vkey = JSON.parse(fs.readFileSync(`${BUILD}/solvency_test.vkey.json`, "utf8"));
if (!(await snarkjs.groth16.verify(vkey, publicSignals, proof))) {
  throw new Error("snarkjs verify failed on freshly generated proof");
}
if (BigInt(publicSignals[0]) !== tree.root || BigInt(publicSignals[1]) !== tree.total) {
  throw new Error("public signals do not match SDK root/total");
}

// All field-element and curve-point encoding is delegated to @attestar/sdk so
// this script and the app share exactly one byte-level implementation.
const hex = {
  alpha: toHex(encodeG1(vkey.vk_alpha_1)),
  beta: toHex(encodeG2(vkey.vk_beta_2)),
  gamma: toHex(encodeG2(vkey.vk_gamma_2)),
  delta: toHex(encodeG2(vkey.vk_delta_2)),
  ic: vkey.IC.map((p) => toHex(encodeG1(p))),
  proof_a: toHex(encodeG1(proof.pi_a)),
  proof_b: toHex(encodeG2(proof.pi_b)),
  proof_c: toHex(encodeG1(proof.pi_c)),
  pub: publicSignals.map((s) => toHex(fieldToBytes(s))),
};

fs.writeFileSync(OUT_JSON, JSON.stringify(hex, null, 2));

const arr = (h) => {
  const out = [];
  for (let i = 0; i < h.length; i += 2) out.push("0x" + h.slice(i, i + 2));
  return "[" + out.join(", ") + "]";
};
const arrList = (hs, size) =>
  `[\n        ${hs.map(arr).join(",\n        ")}\n    ]`;

const rs = `// @generated by packages/circuits/scripts/encode.mjs (legacy depth-2 fixtures) - do not edit by hand.
// Real depth-2 Groth16 proof + verifying key for the Soroban verifier test.
#![cfg(test)]

pub const ALPHA: [u8; 64] = ${arr(hex.alpha)};
pub const BETA: [u8; 128] = ${arr(hex.beta)};
pub const GAMMA: [u8; 128] = ${arr(hex.gamma)};
pub const DELTA: [u8; 128] = ${arr(hex.delta)};
pub const IC: [[u8; 64]; ${hex.ic.length}] = ${arrList(hex.ic)};
pub const PROOF_A: [u8; 64] = ${arr(hex.proof_a)};
pub const PROOF_B: [u8; 128] = ${arr(hex.proof_b)};
pub const PROOF_C: [u8; 64] = ${arr(hex.proof_c)};
pub const PUB: [[u8; 32]; ${hex.pub.length}] = ${arrList(hex.pub)};
`;

// Refuse to clobber a file another generator owns.
if (fs.existsSync(OUT_RS) && fs.readFileSync(OUT_RS, "utf8").includes("encode_p.mjs")) {
  console.error(`refusing to overwrite ${OUT_RS}: it was generated by encode_p.mjs`);
  process.exit(1);
}
fs.writeFileSync(OUT_RS, rs);
console.log("wrote", OUT_RS, "and", OUT_JSON);
console.log("public signals (root, total):", publicSignals.join(", "));
process.exit(0);
